version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be_hanu_sourviner_api
    restart: always
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    # networks:
    #   - internal_network

  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    # networks:
    #   - internal_network

# networks:
#   internal_network:
#     internal: true

volumes:
  mysql_data:
