version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    # networks:
    #   - internal_network

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_DB: $DATABASE_NAME
      # TZ: 'GMT'
      # PGTZ: 'GMT'
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_sourviner:/var/lib/postgresql/data
    env_file:
      - .env
    # networks:
    #   - internal_network

# networks:
#   internal_network:
#     internal: true

volumes:
  postgres_data_sourviner:
